# Generated by Django 4.2.3 on 2024-11-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
            ],
            options={
                'verbose_name': 'глава',
                'verbose_name_plural': 'главы',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=200, verbose_name='имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='фамилия')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('year', models.DateField(verbose_name='год')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auths.customuser')),
                ('dolzhnost', models.CharField(max_length=100, verbose_name='должность')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
            },
            bases=('auths.customuser',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_rate', models.FloatField(verbose_name='рейтинг')),
                ('problem', models.TextField(verbose_name='описание')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auths.chapter', verbose_name='глава')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auths.tutor', verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auths.subject', verbose_name='предмет'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auths.customuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auths.group', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
            },
            bases=('auths.customuser',),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('DON', 'Done'), ('INA', 'Inactive'), ('OCH', 'On checking')], default='INA', max_length=3, verbose_name='статус')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auths.task', verbose_name='задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auths.student', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
            },
        ),
    ]
